//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_Layer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookfineTable
    {
        public int BookFineID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> FineDate { get; set; }
        public Nullable<double> FineAmount { get; set; }
        public Nullable<double> ReceiveAmount { get; set; }
        public Nullable<int> NoOfDays { get; set; }
    
        public virtual BookTable BookTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
